pipeline:
  Linux-386--debian:
    image: debian:stable-slim
    group: build
    commands:
      - dpkg --add-architecture i386
      - apt update >/dev/null
      - apt install -yy binutils:i386 gcc:i386 libc6-dev-i386 libx11-dev:i386 libxext-dev:i386 zip:i386 >/dev/null
      - ./utils/tomo-dev.sh build-Linux `pwd`
      - rm -rf .git .hg
      - zip -r "tomo-Linux-386--debian-$CI_COMMIT_SHA-$CI_BUILD_STARTED.zip" *
      - ./utils/tomo-dev.sh upload-ci "tomo-Linux-386--debian-$CI_COMMIT_SHA-$CI_BUILD_STARTED.zip"
#  Linux-386--ubuntu:
#    image: ubuntu:bionic
#    group: build
#    commands:
#      - dpkg --add-architecture i386
#      - apt update >/dev/null
#      - apt install -yy binutils:i386 gcc:i386 libc6-dev-i386 libx11-dev:i386 libxext-dev:i386 zip:i386 >/dev/null
#      - ./tomo-dev.sh build-Linux `pwd`
#      - rm -rf .git .hg
#      - zip -r "tomo-Linux-386--ubuntu-$CI_COMMIT_SHA-$CI_BUILD_STARTED.zip" *
#      - ./tomo-dev.sh upload-ci "tomo-Linux-386--ubuntu-$CI_COMMIT_SHA-$CI_BUILD_STARTED.zip"
