#!/dis/sh
load std
load arg
user = ''
args  := $*
(arg
	u+  {user=$arg}
	- $args
)
if {test -f /env/user} {
	echo $user >/dev/user
}
if {test -f /env/emuroot} {
	bind '#U*/home' /usr
	if {test -f /env/user} {
		home = /usr/^$user
		cd $home
	}
}
@ wm/qwm /lib/qwmsetup
