#!/dis/sh
load std
load arg

user = ''
args := $*

(arg
	u+ {user=$arg}
	- $args)

if {test -f /env/emuroot} {
	## bind homedir
	bind '#U*/home' /usr
	## set user home
	home = /usr/^$"user
	if {test -d $"home} {
		cd $home
		## setup scripts
		## run tomorc or default desktop
		## alt desktop options:
		## ```
		## @ wm/qwm /lib/qwmsetup
		## ```
		if {test -f $home/lib/tomorc} {
			echo running $home/lib/tomorc >[1=2]
			env >[1=2]
			@ $home/lib/tomorc
		} {
			env >[1=2]
			@ wm/wm wm/logon -u $"user
		}
	} {
		echo '[tomo-init] /env/home is missing!' $"user $"home >[1=2]
		ls /usr >[1=2]
	}
}

