#!/dis/sh.dis
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>
# <https://source.heropunch.luxe/System/9/inferno-attrfs>
# <https://github.com/mjl-/attrfs>
ifs='
'
load std

subfn mquote {
	(arg rem)=$*
	result=$arg
	if{! ~ $arg ''''''} {
		result=${quote $arg}
	}
}

if{! ~ $#* 1} {
	echo 'usage: mkaudiodb path' >[1=2]
	raise fail:usage
}

(dest rem)=$*
for i in `{du -a $dest | sed -n 's,^[^/]*(/.*\.mp3$),\1,p'} {
	lines=`{mp3tag $i | sed 's/^$/''''/'}
	if{~ $status ''} {
		(title artist album year comment track genre)=$lines
		echo -n 'title='^${mquote $title}
		echo -n '	artist='^${mquote $artist}
		echo -n '	album='^${mquote $album}
		echo -n '	year='^${mquote $year}
		echo -n '	comment='^${mquote $comment}
		echo -n '	track='^${mquote $track}
		echo -n '	genre='^${mquote $genre}
		echo -n '	path='^${mquote $i}
		echo
	} {
		echo failed: $i >[1=2]
	}
}
